using Sandbox.Game.EntityComponents;
using Sandbox.ModAPI.Ingame;
using Sandbox.ModAPI.Interfaces;
using SpaceEngineers.Game.ModAPI.Ingame;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using System.Text;
using System;
using VRage;
using VRage.Collections;
using VRage.Game.Components;
using VRage.Game.ModAPI.Ingame;
using VRage.Game.ModAPI.Ingame.Utilities;
using VRage.Game.ObjectBuilders.Definitions;
using VRage.Game;
using VRageMath;

namespace IngameScript
{
    partial class Program
    {
        public class BlockDefinitions
        {
            Dictionary<string, BlockDefinition> blockDefinitions = new Dictionary<string, BlockDefinition>();

            public void FillDictionary()
            {
                blockDefinitions["CubeBlock/Monolith"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 130), new Component("Superconductor", 130), });
                blockDefinitions["CubeBlock/Stereolith"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 130), new Component("Superconductor", 130), });
                blockDefinitions["CubeBlock/DeadAstronaut"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 13), new Component("Superconductor", 13), });
                blockDefinitions["CubeBlock/LargeDeadAstronaut"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 13), new Component("Superconductor", 13), });
                blockDefinitions["BatteryBlock/LargeBlockBatteryBlock"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 20), new Component("Construction", 10), new Component("PowerCell", 80), new Component("Computer", 25), new Component("Construction", 20), new Component("SteelPlate", 60), });
                blockDefinitions["BatteryBlock/SmallBlockBatteryBlock"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 5), new Component("Construction", 2), new Component("PowerCell", 20), new Component("Computer", 2), new Component("Construction", 3), new Component("SteelPlate", 20), });
                blockDefinitions["BatteryBlock/SmallBlockSmallBatteryBlock"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 2), new Component("Construction", 1), new Component("PowerCell", 2), new Component("Computer", 2), new Component("Construction", 1), new Component("SteelPlate", 2), });
                blockDefinitions["CubeBlock/LargeBlockArmorBlock"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 20), new Component("SteelPlate", 5), });
                blockDefinitions["CubeBlock/LargeBlockArmorSlope"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 10), new Component("SteelPlate", 3), });
                blockDefinitions["CubeBlock/LargeBlockArmorCorner"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 3), new Component("SteelPlate", 1), });
                blockDefinitions["CubeBlock/LargeBlockArmorCornerInv"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 16), new Component("SteelPlate", 5), });
                blockDefinitions["CubeBlock/LargeRoundArmor_Slope"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 10), new Component("SteelPlate", 3), });
                blockDefinitions["CubeBlock/LargeRoundArmor_Corner"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 3), new Component("SteelPlate", 1), });
                blockDefinitions["CubeBlock/LargeRoundArmor_CornerInv"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 16), new Component("SteelPlate", 5), });
                blockDefinitions["CubeBlock/LargeHeavyBlockArmorBlock"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 135), new Component("MetalGrid", 50), new Component("SteelPlate", 15), });
                blockDefinitions["CubeBlock/LargeHeavyBlockArmorSlope"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 65), new Component("MetalGrid", 25), new Component("SteelPlate", 10), });
                blockDefinitions["CubeBlock/LargeHeavyBlockArmorCorner"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 20), new Component("MetalGrid", 10), new Component("SteelPlate", 5), });
                blockDefinitions["CubeBlock/LargeHeavyBlockArmorCornerInv"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 110), new Component("MetalGrid", 50), new Component("SteelPlate", 15), });
                blockDefinitions["CubeBlock/SmallBlockArmorBlock"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 1), });
                blockDefinitions["CubeBlock/SmallBlockArmorSlope"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 1), });
                blockDefinitions["CubeBlock/SmallBlockArmorCorner"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 1), });
                blockDefinitions["CubeBlock/SmallBlockArmorCornerInv"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 1), });
                blockDefinitions["CubeBlock/SmallHeavyBlockArmorBlock"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 3), new Component("MetalGrid", 2), new Component("SteelPlate", 2), });
                blockDefinitions["CubeBlock/SmallHeavyBlockArmorSlope"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 2), new Component("MetalGrid", 1), new Component("SteelPlate", 1), });
                blockDefinitions["CubeBlock/SmallHeavyBlockArmorCorner"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 1), new Component("MetalGrid", 1), new Component("SteelPlate", 1), });
                blockDefinitions["CubeBlock/SmallHeavyBlockArmorCornerInv"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 2), new Component("MetalGrid", 1), new Component("SteelPlate", 2), });
                blockDefinitions["CubeBlock/LargeHalfArmorBlock"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 10), new Component("SteelPlate", 2), });
                blockDefinitions["CubeBlock/LargeHeavyHalfArmorBlock"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 50), new Component("MetalGrid", 25), new Component("SteelPlate", 25), });
                blockDefinitions["CubeBlock/LargeHalfSlopeArmorBlock"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 5), new Component("SteelPlate", 2), });
                blockDefinitions["CubeBlock/LargeHeavyHalfSlopeArmorBlock"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 30), new Component("MetalGrid", 15), new Component("SteelPlate", 15), });
                blockDefinitions["CubeBlock/HalfArmorBlock"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 1), });
                blockDefinitions["CubeBlock/HeavyHalfArmorBlock"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 2), new Component("MetalGrid", 1), new Component("SteelPlate", 1), });
                blockDefinitions["CubeBlock/HalfSlopeArmorBlock"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 1), });
                blockDefinitions["CubeBlock/HeavyHalfSlopeArmorBlock"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 1), new Component("MetalGrid", 1), new Component("SteelPlate", 1), });
                blockDefinitions["CubeBlock/LargeBlockArmorRoundSlope"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 10), new Component("SteelPlate", 3), });
                blockDefinitions["CubeBlock/LargeBlockArmorRoundCorner"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 3), new Component("SteelPlate", 1), });
                blockDefinitions["CubeBlock/LargeBlockArmorRoundCornerInv"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 16), new Component("SteelPlate", 5), });
                blockDefinitions["CubeBlock/LargeHeavyBlockArmorRoundSlope"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 115), new Component("MetalGrid", 50), new Component("SteelPlate", 15), });
                blockDefinitions["CubeBlock/LargeHeavyBlockArmorRoundCorner"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 110), new Component("MetalGrid", 40), new Component("SteelPlate", 15), });
                blockDefinitions["CubeBlock/LargeHeavyBlockArmorRoundCornerInv"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 125), new Component("MetalGrid", 50), new Component("SteelPlate", 15), });
                blockDefinitions["CubeBlock/SmallBlockArmorRoundSlope"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 1), });
                blockDefinitions["CubeBlock/SmallBlockArmorRoundCorner"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 1), });
                blockDefinitions["CubeBlock/SmallBlockArmorRoundCornerInv"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 1), });
                blockDefinitions["CubeBlock/SmallHeavyBlockArmorRoundSlope"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 2), new Component("MetalGrid", 1), new Component("SteelPlate", 2), });
                blockDefinitions["CubeBlock/SmallHeavyBlockArmorRoundCorner"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 2), new Component("MetalGrid", 1), new Component("SteelPlate", 2), });
                blockDefinitions["CubeBlock/SmallHeavyBlockArmorRoundCornerInv"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 3), new Component("MetalGrid", 1), new Component("SteelPlate", 2), });
                blockDefinitions["CubeBlock/LargeBlockArmorSlope2Base"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 15), new Component("SteelPlate", 4), });
                blockDefinitions["CubeBlock/LargeBlockArmorSlope2Tip"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 5), new Component("SteelPlate", 2), });
                blockDefinitions["CubeBlock/LargeBlockArmorCorner2Base"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 8), new Component("SteelPlate", 2), });
                blockDefinitions["CubeBlock/LargeBlockArmorCorner2Tip"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 3), new Component("SteelPlate", 1), });
                blockDefinitions["CubeBlock/LargeBlockArmorInvCorner2Base"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 18), new Component("SteelPlate", 4), });
                blockDefinitions["CubeBlock/LargeBlockArmorInvCorner2Tip"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 13), new Component("SteelPlate", 3), });
                blockDefinitions["CubeBlock/LargeHeavyBlockArmorSlope2Base"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 100), new Component("MetalGrid", 45), new Component("SteelPlate", 12), });
                blockDefinitions["CubeBlock/LargeHeavyBlockArmorSlope2Tip"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 30), new Component("MetalGrid", 6), new Component("SteelPlate", 5), });
                blockDefinitions["CubeBlock/LargeHeavyBlockArmorCorner2Base"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 50), new Component("MetalGrid", 15), new Component("SteelPlate", 5), });
                blockDefinitions["CubeBlock/LargeHeavyBlockArmorCorner2Tip"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 17), new Component("MetalGrid", 6), new Component("SteelPlate", 2), });
                blockDefinitions["CubeBlock/LargeHeavyBlockArmorInvCorner2Base"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 120), new Component("MetalGrid", 45), new Component("SteelPlate", 13), });
                blockDefinitions["CubeBlock/LargeHeavyBlockArmorInvCorner2Tip"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 84), new Component("MetalGrid", 25), new Component("SteelPlate", 10), });
                blockDefinitions["CubeBlock/SmallBlockArmorSlope2Base"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 1), });
                blockDefinitions["CubeBlock/SmallBlockArmorSlope2Tip"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 1), });
                blockDefinitions["CubeBlock/SmallBlockArmorCorner2Base"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 1), });
                blockDefinitions["CubeBlock/SmallBlockArmorCorner2Tip"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 1), });
                blockDefinitions["CubeBlock/SmallBlockArmorInvCorner2Base"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 1), });
                blockDefinitions["CubeBlock/SmallBlockArmorInvCorner2Tip"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 1), });
                blockDefinitions["CubeBlock/SmallHeavyBlockArmorSlope2Base"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 2), new Component("MetalGrid", 1), new Component("SteelPlate", 2), });
                blockDefinitions["CubeBlock/SmallHeavyBlockArmorSlope2Tip"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 1), new Component("MetalGrid", 1), new Component("SteelPlate", 1), });
                blockDefinitions["CubeBlock/SmallHeavyBlockArmorCorner2Base"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 2), new Component("MetalGrid", 1), new Component("SteelPlate", 1), });
                blockDefinitions["CubeBlock/SmallHeavyBlockArmorCorner2Tip"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 1), new Component("MetalGrid", 1), new Component("SteelPlate", 1), });
                blockDefinitions["CubeBlock/SmallHeavyBlockArmorInvCorner2Base"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 3), new Component("MetalGrid", 1), new Component("SteelPlate", 2), });
                blockDefinitions["CubeBlock/SmallHeavyBlockArmorInvCorner2Tip"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 3), new Component("MetalGrid", 1), new Component("SteelPlate", 2), });
                blockDefinitions["TerminalBlock/ControlPanel"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 1), new Component("Construction", 1), new Component("Computer", 1), new Component("Display", 1), });
                blockDefinitions["MyProgrammableBlock/SmallProgrammableBlock"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 1), new Component("Construction", 2), new Component("LargeTube", 2), new Component("Motor", 1), new Component("Display", 1), new Component("Computer", 2), new Component("SteelPlate", 1), });
                blockDefinitions["TerminalBlock/SmallControlPanel"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 1), new Component("Construction", 1), new Component("Computer", 1), new Component("Display", 1), });
                blockDefinitions["LargeGatlingTurret/(null)"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 5), new Component("Construction", 25), new Component("MetalGrid", 15), new Component("SmallTube", 6), new Component("Motor", 8), new Component("Computer", 10), new Component("Construction", 5), new Component("SteelPlate", 15), });
                blockDefinitions["LargeGatlingTurret/SmallGatlingTurret"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 5), new Component("Construction", 25), new Component("MetalGrid", 5), new Component("SmallTube", 6), new Component("Motor", 4), new Component("Computer", 10), new Component("Construction", 5), new Component("SteelPlate", 5), });
                blockDefinitions["LargeMissileTurret/(null)"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 5), new Component("Construction", 30), new Component("MetalGrid", 5), new Component("LargeTube", 6), new Component("Motor", 16), new Component("Computer", 12), new Component("Construction", 10), new Component("SteelPlate", 15), });
                blockDefinitions["LargeMissileTurret/SmallMissileTurret"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 5), new Component("Construction", 30), new Component("MetalGrid", 2), new Component("LargeTube", 2), new Component("Motor", 8), new Component("Computer", 12), new Component("Construction", 10), new Component("SteelPlate", 5), });
                blockDefinitions["InteriorTurret/LargeInteriorTurret"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 6), new Component("Construction", 15), new Component("SmallTube", 1), new Component("Motor", 2), new Component("Computer", 5), new Component("Construction", 5), new Component("SteelPlate", 4), });
                blockDefinitions["Passage/(null)"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 74), new Component("Construction", 20), new Component("SmallTube", 48), });
                blockDefinitions["Ladder2/(null)"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 10), new Component("Construction", 10), new Component("SmallTube", 10), new Component("Construction", 10), });
                blockDefinitions["Door/(null)"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 4), new Component("Construction", 15), new Component("SmallTube", 4), new Component("Motor", 2), new Component("Display", 1), new Component("Computer", 2), new Component("InteriorPlate", 6), new Component("Construction", 25), new Component("SteelPlate", 8), });
                blockDefinitions["RadioAntenna/LargeBlockRadioAntenna"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 60), new Component("LargeTube", 40), new Component("SmallTube", 60), new Component("Construction", 30), new Component("Computer", 8), new Component("RadioCommunication", 40), new Component("SteelPlate", 20), });
                blockDefinitions["Beacon/LargeBlockBeacon"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 40), new Component("Construction", 30), new Component("LargeTube", 20), new Component("Computer", 10), new Component("RadioCommunication", 40), new Component("SteelPlate", 40), });
                blockDefinitions["Beacon/SmallBlockBeacon"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 1), new Component("Construction", 1), new Component("SmallTube", 1), new Component("Computer", 1), new Component("RadioCommunication", 4), new Component("SteelPlate", 1), });
                blockDefinitions["ReflectorLight/LargeBlockFrontLight"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 8), new Component("LargeTube", 2), new Component("InteriorPlate", 20), new Component("Construction", 15), new Component("BulletproofGlass", 4), });
                blockDefinitions["InteriorLight/SmallLight"] = new BlockDefinition(new Component[] { new Component("Construction", 2), });
                blockDefinitions["InteriorLight/SmallBlockSmallLight"] = new BlockDefinition(new Component[] { new Component("Construction", 2), });
                blockDefinitions["InteriorLight/LargeBlockLight_1corner"] = new BlockDefinition(new Component[] { new Component("Construction", 3), });
                blockDefinitions["InteriorLight/LargeBlockLight_2corner"] = new BlockDefinition(new Component[] { new Component("Construction", 6), });
                blockDefinitions["InteriorLight/SmallBlockLight_1corner"] = new BlockDefinition(new Component[] { new Component("Construction", 2), });
                blockDefinitions["InteriorLight/SmallBlockLight_2corner"] = new BlockDefinition(new Component[] { new Component("Construction", 4), });
                blockDefinitions["CubeBlock/LargeWindowSquare"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 12), new Component("Construction", 8), new Component("SmallTube", 4), });
                blockDefinitions["CubeBlock/LargeWindowEdge"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 16), new Component("Construction", 12), new Component("SmallTube", 6), });
                blockDefinitions["CubeBlock/LargeStairs"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 40), new Component("Construction", 30), new Component("InteriorPlate", 10), });
                blockDefinitions["CubeBlock/LargeRamp"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 60), new Component("Construction", 16), new Component("InteriorPlate", 10), });
                blockDefinitions["CubeBlock/LargeSteelCatwalk"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 20), new Component("Construction", 5), new Component("SmallTube", 20), new Component("InteriorPlate", 7), });
                blockDefinitions["CubeBlock/LargeSteelCatwalk2Sides"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 20), new Component("Construction", 7), new Component("SmallTube", 25), new Component("InteriorPlate", 12), });
                blockDefinitions["CubeBlock/LargeSteelCatwalkCorner"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 20), new Component("Construction", 7), new Component("SmallTube", 25), new Component("InteriorPlate", 12), });
                blockDefinitions["CubeBlock/LargeSteelCatwalkPlate"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 15), new Component("Construction", 7), new Component("SmallTube", 17), new Component("InteriorPlate", 8), });
                blockDefinitions["CubeBlock/LargeCoverWall"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 4), new Component("Construction", 10), });
                blockDefinitions["CubeBlock/LargeCoverWallHalf"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 2), new Component("Construction", 6), });
                blockDefinitions["Warhead/LargeWarhead"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 10), new Component("Girder", 24), new Component("Construction", 12), new Component("SmallTube", 12), new Component("Computer", 2), new Component("Explosives", 6), new Component("SteelPlate", 10), });
                blockDefinitions["Warhead/SmallWarhead"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 1), new Component("Girder", 1), new Component("Construction", 1), new Component("SmallTube", 2), new Component("Computer", 1), new Component("Explosives", 2), new Component("SteelPlate", 3), });
                blockDefinitions["Decoy/LargeDecoy"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 10), new Component("Construction", 10), new Component("Computer", 10), new Component("RadioCommunication", 1), new Component("LargeTube", 2), new Component("SteelPlate", 20), });
                blockDefinitions["Decoy/SmallDecoy"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 1), new Component("Construction", 1), new Component("Computer", 1), new Component("RadioCommunication", 1), new Component("SmallTube", 2), new Component("SteelPlate", 1), });
                blockDefinitions["CubeBlock/LargeBlockInteriorWall"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 20), new Component("Construction", 8), new Component("InteriorPlate", 5), new Component("Construction", 2), });
                blockDefinitions["CubeBlock/LargeInteriorPillar"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 25), new Component("Construction", 10), new Component("SmallTube", 4), });
                blockDefinitions["LandingGear/LargeBlockLandingGear"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 100), new Component("Construction", 20), new Component("Motor", 6), new Component("SteelPlate", 50), });
                blockDefinitions["Projector/LargeProjector"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 11), new Component("Construction", 4), new Component("LargeTube", 2), new Component("Motor", 1), new Component("Computer", 2), new Component("SteelPlate", 10), });
                blockDefinitions["Projector/SmallProjector"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 1), new Component("Construction", 2), new Component("LargeTube", 2), new Component("Motor", 1), new Component("Computer", 2), new Component("SteelPlate", 1), });
                blockDefinitions["Refinery/LargeRefinery"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 1100), new Component("Construction", 40), new Component("LargeTube", 20), new Component("Motor", 16), new Component("MetalGrid", 20), new Component("Computer", 20), new Component("SteelPlate", 100), });
                blockDefinitions["Refinery/Blast Furnace"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 100), new Component("Construction", 20), new Component("Motor", 10), new Component("Computer", 10), new Component("SteelPlate", 20), });
                blockDefinitions["OxygenGenerator/(null)"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 110), new Component("Construction", 5), new Component("LargeTube", 2), new Component("Motor", 4), new Component("Computer", 5), new Component("SteelPlate", 10), });
                blockDefinitions["Assembler/LargeAssembler"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 120), new Component("Construction", 80), new Component("Motor", 20), new Component("Display", 10), new Component("MetalGrid", 10), new Component("Computer", 160), new Component("SteelPlate", 20), });
                blockDefinitions["Assembler/BasicAssembler"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 60), new Component("Construction", 40), new Component("Motor", 10), new Component("Display", 4), new Component("Computer", 80), new Component("SteelPlate", 20), });
                blockDefinitions["SurvivalKit/SurvivalKitLarge"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 20), new Component("Construction", 2), new Component("Medical", 3), new Component("Motor", 4), new Component("Display", 1), new Component("Computer", 5), new Component("SteelPlate", 10), });
                blockDefinitions["SurvivalKit/SurvivalKit"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 1), new Component("Construction", 2), new Component("Medical", 3), new Component("Motor", 4), new Component("Display", 1), new Component("Computer", 5), new Component("SteelPlate", 5), });
                blockDefinitions["OreDetector/LargeOreDetector"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 30), new Component("Construction", 40), new Component("Motor", 5), new Component("Computer", 25), new Component("Detector", 20), new Component("SteelPlate", 20), });
                blockDefinitions["MedicalRoom/LargeMedicalRoom"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 220), new Component("Construction", 80), new Component("MetalGrid", 60), new Component("SmallTube", 20), new Component("LargeTube", 5), new Component("Display", 10), new Component("Computer", 10), new Component("Medical", 15), new Component("InteriorPlate", 20), });
                blockDefinitions["GravityGenerator/(null)"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 54), new Component("GravityGenerator", 6), new Component("Construction", 60), new Component("SteelPlate", 56), new Component("LargeTube", 4), new Component("Motor", 6), new Component("Computer", 40), new Component("SteelPlate", 40), });
                blockDefinitions["GravityGeneratorSphere/(null)"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 54), new Component("GravityGenerator", 6), new Component("Construction", 60), new Component("SteelPlate", 56), new Component("LargeTube", 4), new Component("Motor", 6), new Component("Computer", 40), new Component("SteelPlate", 40), });
                blockDefinitions["JumpDrive/LargeJumpDrive"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 40), new Component("MetalGrid", 50), new Component("GravityGenerator", 20), new Component("Detector", 20), new Component("PowerCell", 120), new Component("Superconductor", 1000), new Component("Computer", 300), new Component("Construction", 40), new Component("SteelPlate", 20), });
                blockDefinitions["Cockpit/LargeBlockCockpit"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 10), new Component("Construction", 15), new Component("Motor", 2), new Component("Computer", 100), new Component("Display", 10), new Component("Construction", 5), new Component("InteriorPlate", 10), });
                blockDefinitions["Cockpit/LargeBlockCockpitSeat"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 20), new Component("Construction", 20), new Component("Motor", 1), new Component("Display", 8), new Component("Computer", 100), new Component("SteelPlate", 10), new Component("BulletproofGlass", 60), });
                blockDefinitions["Cockpit/SmallBlockCockpit"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 5), new Component("Construction", 10), new Component("Motor", 1), new Component("Display", 5), new Component("Computer", 15), new Component("SteelPlate", 5), new Component("BulletproofGlass", 30), });
                blockDefinitions["Cockpit/DBSmallBlockFighterCockpit"] = new BlockDefinition(new Component[] { new Component("Construction", 20), new Component("Motor", 1), new Component("SteelPlate", 10), new Component("MetalGrid", 10), new Component("InteriorPlate", 15), new Component("Display", 4), new Component("Computer", 20), new Component("BulletproofGlass", 40), new Component("SteelPlate", 10), });
                blockDefinitions["Cockpit/CockpitOpen"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 10), new Component("Construction", 15), new Component("Motor", 2), new Component("Computer", 100), new Component("Display", 4), new Component("Construction", 5), new Component("InteriorPlate", 10), });
                blockDefinitions["Cockpit/PassengerSeatLarge"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 10), new Component("Construction", 20), new Component("InteriorPlate", 10), });
                blockDefinitions["Cockpit/PassengerSeatSmall"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 10), new Component("Construction", 20), new Component("InteriorPlate", 10), });
                blockDefinitions["CryoChamber/LargeBlockCryoChamber"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 30), new Component("Construction", 20), new Component("Motor", 8), new Component("Display", 8), new Component("Computer", 30), new Component("InteriorPlate", 10), new Component("BulletproofGlass", 10), });
                blockDefinitions["LandingGear/SmallBlockLandingGear"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 1), new Component("Construction", 5), new Component("Motor", 1), new Component("SteelPlate", 1), });
                blockDefinitions["ReflectorLight/SmallBlockFrontLight"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 1), new Component("LargeTube", 1), new Component("InteriorPlate", 1), new Component("Construction", 1), new Component("BulletproofGlass", 2), });
                blockDefinitions["SmallMissileLauncher/(null)"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 1), new Component("Construction", 2), new Component("MetalGrid", 1), new Component("LargeTube", 4), new Component("Motor", 1), new Component("Computer", 1), new Component("SteelPlate", 3), });
                blockDefinitions["SmallMissileLauncher/LargeMissileLauncher"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 20), new Component("Construction", 8), new Component("MetalGrid", 30), new Component("LargeTube", 25), new Component("Motor", 6), new Component("Computer", 4), new Component("SteelPlate", 15), });
                blockDefinitions["SmallMissileLauncherReload/SmallRocketLauncherReload"] = new BlockDefinition(new Component[] { new Component("SmallTube", 50), new Component("InteriorPlate", 40), new Component("Construction", 24), new Component("LargeTube", 8), new Component("MetalGrid", 10), new Component("Motor", 4), new Component("Computer", 2), new Component("SteelPlate", 8), new Component("InteriorPlate", 10), });
                blockDefinitions["SmallGatlingGun/(null)"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 1), new Component("Construction", 1), new Component("MetalGrid", 2), new Component("SmallTube", 6), new Component("Motor", 1), new Component("Computer", 1), new Component("SteelPlate", 3), });
                blockDefinitions["Drill/SmallBlockDrill"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 20), new Component("Construction", 30), new Component("LargeTube", 4), new Component("Motor", 1), new Component("Computer", 1), new Component("SteelPlate", 12), });
                blockDefinitions["Drill/LargeBlockDrill"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 180), new Component("Construction", 40), new Component("LargeTube", 12), new Component("Motor", 5), new Component("Computer", 5), new Component("SteelPlate", 120), });
                blockDefinitions["OreDetector/SmallBlockOreDetector"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 1), new Component("Construction", 2), new Component("Motor", 1), new Component("Computer", 1), new Component("Detector", 1), new Component("SteelPlate", 2), });
                blockDefinitions["SensorBlock/SmallBlockSensor"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 5), new Component("Construction", 5), new Component("Computer", 6), new Component("RadioCommunication", 4), new Component("Detector", 6), new Component("SteelPlate", 2), });
                blockDefinitions["SensorBlock/LargeBlockSensor"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 5), new Component("Construction", 5), new Component("Computer", 6), new Component("RadioCommunication", 4), new Component("Detector", 6), new Component("SteelPlate", 2), });
                blockDefinitions["SoundBlock/SmallBlockSoundBlock"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 1), new Component("Construction", 6), new Component("Computer", 3), new Component("InteriorPlate", 3), });
                blockDefinitions["SoundBlock/LargeBlockSoundBlock"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 1), new Component("Construction", 6), new Component("Computer", 3), new Component("InteriorPlate", 3), });
                blockDefinitions["TextPanel/SmallTextPanel"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 1), new Component("Construction", 4), new Component("Computer", 4), new Component("Display", 3), new Component("BulletproofGlass", 1), });
                blockDefinitions["TextPanel/SmallLCDPanelWide"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 1), new Component("Construction", 8), new Component("Computer", 8), new Component("Display", 6), new Component("BulletproofGlass", 2), });
                blockDefinitions["TextPanel/SmallLCDPanel"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 1), new Component("Construction", 4), new Component("Computer", 4), new Component("Display", 3), new Component("BulletproofGlass", 2), });
                blockDefinitions["TextPanel/LargeBlockCorner_LCD_1"] = new BlockDefinition(new Component[] { new Component("Construction", 5), new Component("Computer", 3), new Component("Display", 1), });
                blockDefinitions["TextPanel/LargeBlockCorner_LCD_2"] = new BlockDefinition(new Component[] { new Component("Construction", 5), new Component("Computer", 3), new Component("Display", 1), });
                blockDefinitions["TextPanel/LargeBlockCorner_LCD_Flat_1"] = new BlockDefinition(new Component[] { new Component("Construction", 5), new Component("Computer", 3), new Component("Display", 1), });
                blockDefinitions["TextPanel/LargeBlockCorner_LCD_Flat_2"] = new BlockDefinition(new Component[] { new Component("Construction", 5), new Component("Computer", 3), new Component("Display", 1), });
                blockDefinitions["TextPanel/SmallBlockCorner_LCD_1"] = new BlockDefinition(new Component[] { new Component("Construction", 3), new Component("Computer", 2), new Component("Display", 1), });
                blockDefinitions["TextPanel/SmallBlockCorner_LCD_2"] = new BlockDefinition(new Component[] { new Component("Construction", 3), new Component("Computer", 2), new Component("Display", 1), });
                blockDefinitions["TextPanel/SmallBlockCorner_LCD_Flat_1"] = new BlockDefinition(new Component[] { new Component("Construction", 3), new Component("Computer", 2), new Component("Display", 1), });
                blockDefinitions["TextPanel/SmallBlockCorner_LCD_Flat_2"] = new BlockDefinition(new Component[] { new Component("Construction", 3), new Component("Computer", 2), new Component("Display", 1), });
                blockDefinitions["OxygenTank/OxygenTankSmall"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 10), new Component("LargeTube", 8), new Component("SmallTube", 10), new Component("Computer", 8), new Component("Construction", 10), new Component("SteelPlate", 6), });
                blockDefinitions["OxygenGenerator/OxygenGeneratorSmall"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 6), new Component("Construction", 8), new Component("LargeTube", 2), new Component("Motor", 1), new Component("Computer", 3), new Component("SteelPlate", 2), });
                blockDefinitions["TextPanel/LargeTextPanel"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 1), new Component("Construction", 6), new Component("Computer", 6), new Component("Display", 10), new Component("BulletproofGlass", 2), });
                blockDefinitions["TextPanel/LargeLCDPanel"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 1), new Component("Construction", 6), new Component("Computer", 6), new Component("Display", 10), new Component("BulletproofGlass", 6), });
                blockDefinitions["TextPanel/LargeLCDPanelWide"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 2), new Component("Construction", 12), new Component("Computer", 12), new Component("Display", 20), new Component("BulletproofGlass", 12), });
                blockDefinitions["RadioAntenna/SmallBlockRadioAntenna"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 1), new Component("SmallTube", 1), new Component("Construction", 1), new Component("Computer", 1), new Component("RadioCommunication", 4), new Component("Construction", 1), });
                blockDefinitions["RemoteControl/LargeBlockRemoteControl"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 5), new Component("Construction", 10), new Component("Motor", 1), new Component("Computer", 15), new Component("InteriorPlate", 5), });
                blockDefinitions["RemoteControl/SmallBlockRemoteControl"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 1), new Component("Construction", 1), new Component("Motor", 1), new Component("Computer", 1), new Component("InteriorPlate", 1), });
                blockDefinitions["AirVent/(null)"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 30), new Component("Construction", 20), new Component("Motor", 10), new Component("Computer", 5), new Component("SteelPlate", 15), });
                blockDefinitions["AirVent/SmallAirVent"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 5), new Component("Construction", 10), new Component("Motor", 2), new Component("Computer", 5), new Component("SteelPlate", 3), });
                blockDefinitions["OxygenTank/(null)"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 60), new Component("LargeTube", 40), new Component("SmallTube", 60), new Component("Computer", 8), new Component("Construction", 40), new Component("SteelPlate", 20), });
                blockDefinitions["OxygenTank/LargeHydrogenTank"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 160), new Component("LargeTube", 80), new Component("SmallTube", 60), new Component("Computer", 8), new Component("Construction", 40), new Component("SteelPlate", 120), });
                blockDefinitions["OxygenTank/SmallHydrogenTank"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 60), new Component("LargeTube", 40), new Component("SmallTube", 60), new Component("Computer", 8), new Component("Construction", 40), new Component("SteelPlate", 20), });
                blockDefinitions["UpgradeModule/LargeProductivityModule"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 80), new Component("Construction", 40), new Component("SmallTube", 20), new Component("Computer", 60), new Component("Motor", 4), new Component("SteelPlate", 20), });
                blockDefinitions["UpgradeModule/LargeEffectivenessModule"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 80), new Component("Construction", 50), new Component("SmallTube", 15), new Component("Superconductor", 20), new Component("Motor", 4), new Component("SteelPlate", 20), });
                blockDefinitions["UpgradeModule/LargeEnergyModule"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 80), new Component("Construction", 40), new Component("SmallTube", 20), new Component("PowerCell", 20), new Component("Motor", 4), new Component("SteelPlate", 20), });
                blockDefinitions["CargoContainer/SmallBlockSmallContainer"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 2), new Component("Construction", 1), new Component("Computer", 1), new Component("Motor", 1), new Component("Display", 1), new Component("InteriorPlate", 1), });
                blockDefinitions["CargoContainer/SmallBlockMediumContainer"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 20), new Component("Construction", 10), new Component("Computer", 4), new Component("Motor", 4), new Component("Display", 1), new Component("InteriorPlate", 10), });
                blockDefinitions["CargoContainer/SmallBlockLargeContainer"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 55), new Component("Construction", 25), new Component("Computer", 6), new Component("Motor", 8), new Component("Display", 1), new Component("InteriorPlate", 20), });
                blockDefinitions["CargoContainer/LargeBlockSmallContainer"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 30), new Component("Construction", 35), new Component("MetalGrid", 4), new Component("SmallTube", 20), new Component("Motor", 4), new Component("Display", 1), new Component("Computer", 2), new Component("Construction", 5), new Component("InteriorPlate", 10), });
                blockDefinitions["CargoContainer/LargeBlockLargeContainer"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 300), new Component("Construction", 60), new Component("MetalGrid", 24), new Component("SmallTube", 60), new Component("Motor", 20), new Component("Display", 1), new Component("Computer", 8), new Component("Construction", 20), new Component("InteriorPlate", 60), });
                blockDefinitions["Thrust/SmallBlockSmallThrust"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 1), new Component("Construction", 1), new Component("LargeTube", 1), new Component("Thrust", 1), new Component("Construction", 1), new Component("SteelPlate", 1), });
                blockDefinitions["Thrust/SmallBlockLargeThrust"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 1), new Component("Construction", 1), new Component("LargeTube", 5), new Component("Thrust", 12), new Component("Construction", 1), new Component("SteelPlate", 4), });
                blockDefinitions["Thrust/LargeBlockSmallThrust"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 15), new Component("Construction", 40), new Component("LargeTube", 8), new Component("Thrust", 80), new Component("Construction", 20), new Component("SteelPlate", 10), });
                blockDefinitions["Thrust/LargeBlockLargeThrust"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 100), new Component("Construction", 70), new Component("LargeTube", 40), new Component("Thrust", 960), new Component("Construction", 30), new Component("SteelPlate", 50), });
                blockDefinitions["Thrust/LargeBlockLargeHydrogenThrust"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 100), new Component("Construction", 150), new Component("MetalGrid", 250), new Component("LargeTube", 40), new Component("Construction", 30), new Component("SteelPlate", 50), });
                blockDefinitions["Thrust/LargeBlockSmallHydrogenThrust"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 15), new Component("Construction", 40), new Component("MetalGrid", 40), new Component("LargeTube", 8), new Component("Construction", 20), new Component("SteelPlate", 10), });
                blockDefinitions["Thrust/SmallBlockLargeHydrogenThrust"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 20), new Component("Construction", 20), new Component("MetalGrid", 22), new Component("LargeTube", 10), new Component("Construction", 10), new Component("SteelPlate", 10), });
                blockDefinitions["Thrust/SmallBlockSmallHydrogenThrust"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 2), new Component("Construction", 10), new Component("MetalGrid", 4), new Component("LargeTube", 2), new Component("Construction", 5), new Component("SteelPlate", 5), });
                blockDefinitions["Thrust/LargeBlockLargeAtmosphericThrust"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 100), new Component("Construction", 40), new Component("LargeTube", 50), new Component("MetalGrid", 40), new Component("Motor", 1100), new Component("Construction", 20), new Component("SteelPlate", 130), });
                blockDefinitions["Thrust/LargeBlockSmallAtmosphericThrust"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 15), new Component("Construction", 30), new Component("LargeTube", 8), new Component("MetalGrid", 10), new Component("Motor", 110), new Component("Construction", 20), new Component("SteelPlate", 20), });
                blockDefinitions["Thrust/SmallBlockLargeAtmosphericThrust"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 10), new Component("Construction", 20), new Component("LargeTube", 4), new Component("MetalGrid", 8), new Component("Motor", 90), new Component("Construction", 10), new Component("SteelPlate", 10), });
                blockDefinitions["Thrust/SmallBlockSmallAtmosphericThrust"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 2), new Component("Construction", 20), new Component("LargeTube", 1), new Component("MetalGrid", 1), new Component("Motor", 18), new Component("Construction", 2), new Component("SteelPlate", 1), });
                blockDefinitions["CameraBlock/SmallCameraBlock"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 1), new Component("Computer", 3), new Component("SteelPlate", 1), });
                blockDefinitions["CameraBlock/LargeCameraBlock"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 1), new Component("Computer", 3), new Component("SteelPlate", 1), });
                blockDefinitions["Gyro/LargeBlockGyro"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 500), new Component("Construction", 40), new Component("LargeTube", 4), new Component("MetalGrid", 50), new Component("Motor", 4), new Component("Computer", 5), new Component("SteelPlate", 100), });
                blockDefinitions["Gyro/SmallBlockGyro"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 15), new Component("Construction", 5), new Component("LargeTube", 1), new Component("Motor", 2), new Component("Computer", 3), new Component("SteelPlate", 10), });
                blockDefinitions["Reactor/SmallBlockSmallGenerator"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 1), new Component("Construction", 10), new Component("MetalGrid", 2), new Component("LargeTube", 1), new Component("Reactor", 3), new Component("Motor", 1), new Component("Computer", 10), new Component("SteelPlate", 2), });
                blockDefinitions["Reactor/SmallBlockLargeGenerator"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 40), new Component("Construction", 9), new Component("MetalGrid", 9), new Component("LargeTube", 3), new Component("Reactor", 95), new Component("Motor", 5), new Component("Computer", 25), new Component("SteelPlate", 20), });
                blockDefinitions["Reactor/LargeBlockSmallGenerator"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 50), new Component("Construction", 40), new Component("MetalGrid", 4), new Component("LargeTube", 8), new Component("Reactor", 100), new Component("Motor", 6), new Component("Computer", 25), new Component("SteelPlate", 30), });
                blockDefinitions["Reactor/LargeBlockLargeGenerator"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 800), new Component("Construction", 70), new Component("MetalGrid", 40), new Component("LargeTube", 40), new Component("Superconductor", 100), new Component("Reactor", 2000), new Component("Motor", 20), new Component("Computer", 75), new Component("SteelPlate", 200), });
                blockDefinitions["HydrogenEngine/LargeHydrogenEngine"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 80), new Component("Construction", 60), new Component("LargeTube", 12), new Component("SmallTube", 20), new Component("Motor", 12), new Component("Computer", 4), new Component("PowerCell", 1), new Component("Construction", 10), new Component("SteelPlate", 20), });
                blockDefinitions["HydrogenEngine/SmallHydrogenEngine"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 20), new Component("Construction", 18), new Component("LargeTube", 4), new Component("SmallTube", 6), new Component("Motor", 4), new Component("Computer", 1), new Component("PowerCell", 1), new Component("Construction", 2), new Component("SteelPlate", 10), });
                blockDefinitions["PistonBase/LargePistonBase"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 10), new Component("Construction", 10), new Component("LargeTube", 4), new Component("Motor", 4), new Component("Computer", 2), new Component("SteelPlate", 5), });
                blockDefinitions["ExtendedPistonBase/LargePistonBase"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 10), new Component("Construction", 10), new Component("LargeTube", 4), new Component("Motor", 4), new Component("Computer", 2), new Component("SteelPlate", 5), });
                blockDefinitions["PistonTop/LargePistonTop"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 10), new Component("LargeTube", 8), });
                blockDefinitions["PistonBase/SmallPistonBase"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 2), new Component("Construction", 4), new Component("SmallTube", 4), new Component("Motor", 2), new Component("Computer", 1), new Component("SteelPlate", 2), });
                blockDefinitions["ExtendedPistonBase/SmallPistonBase"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 2), new Component("Construction", 4), new Component("SmallTube", 4), new Component("Motor", 2), new Component("Computer", 1), new Component("SteelPlate", 2), });
                blockDefinitions["PistonTop/SmallPistonTop"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 4), new Component("LargeTube", 2), });
                blockDefinitions["MotorStator/LargeStator"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 10), new Component("Construction", 10), new Component("LargeTube", 4), new Component("Motor", 4), new Component("Computer", 2), new Component("SteelPlate", 5), });
                blockDefinitions["MotorSuspension/Suspension3x3"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 15), new Component("Construction", 15), new Component("LargeTube", 6), new Component("SmallTube", 12), new Component("Motor", 6), new Component("SteelPlate", 10), });
                blockDefinitions["MotorSuspension/Suspension5x5"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 40), new Component("Construction", 40), new Component("LargeTube", 20), new Component("SmallTube", 30), new Component("Motor", 20), new Component("SteelPlate", 30), });
                blockDefinitions["MotorSuspension/Suspension1x1"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 15), new Component("Construction", 15), new Component("LargeTube", 6), new Component("SmallTube", 12), new Component("Motor", 6), new Component("SteelPlate", 10), });
                blockDefinitions["MotorSuspension/SmallSuspension3x3"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 5), new Component("Construction", 7), new Component("SmallTube", 2), new Component("Motor", 1), new Component("SteelPlate", 3), });
                blockDefinitions["MotorSuspension/SmallSuspension5x5"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 10), new Component("Construction", 12), new Component("SmallTube", 4), new Component("Motor", 2), new Component("SteelPlate", 6), });
                blockDefinitions["MotorSuspension/SmallSuspension1x1"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 5), new Component("Construction", 7), new Component("SmallTube", 2), new Component("Motor", 1), new Component("SteelPlate", 3), });
                blockDefinitions["MotorSuspension/Suspension3x3mirrored"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 15), new Component("Construction", 15), new Component("LargeTube", 6), new Component("SmallTube", 12), new Component("Motor", 6), new Component("SteelPlate", 10), });
                blockDefinitions["MotorSuspension/Suspension5x5mirrored"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 40), new Component("Construction", 40), new Component("LargeTube", 20), new Component("SmallTube", 30), new Component("Motor", 20), new Component("SteelPlate", 30), });
                blockDefinitions["MotorSuspension/Suspension1x1mirrored"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 15), new Component("Construction", 15), new Component("LargeTube", 6), new Component("SmallTube", 12), new Component("Motor", 6), new Component("SteelPlate", 10), });
                blockDefinitions["MotorSuspension/SmallSuspension3x3mirrored"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 5), new Component("Construction", 7), new Component("SmallTube", 2), new Component("Motor", 1), new Component("SteelPlate", 3), });
                blockDefinitions["MotorSuspension/SmallSuspension5x5mirrored"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 10), new Component("Construction", 12), new Component("SmallTube", 4), new Component("Motor", 2), new Component("SteelPlate", 6), });
                blockDefinitions["MotorSuspension/SmallSuspension1x1mirrored"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 5), new Component("Construction", 7), new Component("SmallTube", 2), new Component("Motor", 1), new Component("SteelPlate", 3), });
                blockDefinitions["MotorRotor/LargeRotor"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 30), new Component("LargeTube", 6), });
                blockDefinitions["MotorStator/SmallStator"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 3), new Component("Construction", 5), new Component("SmallTube", 1), new Component("Motor", 1), new Component("Computer", 1), new Component("SteelPlate", 2), });
                blockDefinitions["MotorRotor/SmallRotor"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 12), new Component("SmallTube", 6), });
                blockDefinitions["MotorAdvancedStator/LargeAdvancedStator"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 10), new Component("Construction", 10), new Component("LargeTube", 4), new Component("Motor", 4), new Component("Computer", 2), new Component("SteelPlate", 5), });
                blockDefinitions["MotorAdvancedRotor/LargeAdvancedRotor"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 30), new Component("LargeTube", 10), });
                blockDefinitions["MotorAdvancedStator/SmallAdvancedStator"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 3), new Component("Construction", 5), new Component("SmallTube", 1), new Component("Motor", 1), new Component("Computer", 1), new Component("SteelPlate", 2), });
                blockDefinitions["MotorAdvancedRotor/SmallAdvancedRotor"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 30), new Component("LargeTube", 10), });
                blockDefinitions["ButtonPanel/ButtonPanelLarge"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 10), new Component("Construction", 10), new Component("Computer", 20), new Component("Construction", 10), });
                blockDefinitions["ButtonPanel/ButtonPanelSmall"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 2), new Component("Construction", 1), new Component("Computer", 1), new Component("Construction", 1), });
                blockDefinitions["TimerBlock/TimerBlockLarge"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 6), new Component("Construction", 20), new Component("Computer", 5), new Component("Construction", 10), });
                blockDefinitions["TimerBlock/TimerBlockSmall"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 2), new Component("Construction", 2), new Component("Computer", 1), new Component("Construction", 1), });
                blockDefinitions["CubeBlock/LargeRailStraight"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 12), new Component("Construction", 8), new Component("LargeTube", 4), });
                blockDefinitions["WindTurbine/LargeBlockWindTurbine"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 10), new Component("Motor", 8), new Component("Construction", 20), new Component("Girder", 24), new Component("Computer", 2), new Component("InteriorPlate", 30), });
                blockDefinitions["SolarPanel/LargeBlockSolarPanel"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 4), new Component("Construction", 10), new Component("Girder", 12), new Component("Computer", 4), new Component("SolarCell", 32), new Component("Construction", 4), new Component("BulletproofGlass", 4), });
                blockDefinitions["SolarPanel/SmallBlockSolarPanel"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 2), new Component("Construction", 1), new Component("Girder", 4), new Component("Computer", 1), new Component("SolarCell", 8), new Component("Construction", 1), new Component("BulletproofGlass", 1), });
                blockDefinitions["OxygenFarm/LargeBlockOxygenFarm"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 40), new Component("BulletproofGlass", 60), new Component("LargeTube", 20), new Component("SmallTube", 10), new Component("Construction", 20), new Component("Computer", 20), new Component("BulletproofGlass", 40), });
                blockDefinitions["CubeBlock/Window1x2Slope"] = new BlockDefinition(new Component[] { new Component("Girder", 16), new Component("BulletproofGlass", 40), new Component("BulletproofGlass", 15), });
                blockDefinitions["CubeBlock/Window1x2Inv"] = new BlockDefinition(new Component[] { new Component("Girder", 15), new Component("BulletproofGlass", 30), new Component("BulletproofGlass", 10), });
                blockDefinitions["CubeBlock/Window1x2Face"] = new BlockDefinition(new Component[] { new Component("Girder", 15), new Component("BulletproofGlass", 30), new Component("BulletproofGlass", 10), });
                blockDefinitions["CubeBlock/Window1x2SideLeft"] = new BlockDefinition(new Component[] { new Component("Girder", 13), new Component("BulletproofGlass", 20), new Component("BulletproofGlass", 6), });
                blockDefinitions["CubeBlock/Window1x2SideLeftInv"] = new BlockDefinition(new Component[] { new Component("Girder", 13), new Component("BulletproofGlass", 20), new Component("BulletproofGlass", 6), });
                blockDefinitions["CubeBlock/Window1x2SideRight"] = new BlockDefinition(new Component[] { new Component("Girder", 13), new Component("BulletproofGlass", 20), new Component("BulletproofGlass", 6), });
                blockDefinitions["CubeBlock/Window1x2SideRightInv"] = new BlockDefinition(new Component[] { new Component("Girder", 13), new Component("BulletproofGlass", 20), new Component("BulletproofGlass", 6), });
                blockDefinitions["CubeBlock/Window1x1Slope"] = new BlockDefinition(new Component[] { new Component("Girder", 12), new Component("BulletproofGlass", 25), new Component("BulletproofGlass", 10), });
                blockDefinitions["CubeBlock/Window1x1Face"] = new BlockDefinition(new Component[] { new Component("Girder", 11), new Component("BulletproofGlass", 16), new Component("BulletproofGlass", 8), });
                blockDefinitions["CubeBlock/Window1x1Side"] = new BlockDefinition(new Component[] { new Component("Girder", 9), new Component("BulletproofGlass", 12), new Component("BulletproofGlass", 5), });
                blockDefinitions["CubeBlock/Window1x1SideInv"] = new BlockDefinition(new Component[] { new Component("Girder", 9), new Component("BulletproofGlass", 12), new Component("BulletproofGlass", 5), });
                blockDefinitions["CubeBlock/Window1x1Inv"] = new BlockDefinition(new Component[] { new Component("Girder", 11), new Component("BulletproofGlass", 16), new Component("BulletproofGlass", 8), });
                blockDefinitions["CubeBlock/Window1x2Flat"] = new BlockDefinition(new Component[] { new Component("Girder", 15), new Component("BulletproofGlass", 40), new Component("BulletproofGlass", 10), });
                blockDefinitions["CubeBlock/Window1x2FlatInv"] = new BlockDefinition(new Component[] { new Component("Girder", 15), new Component("BulletproofGlass", 35), new Component("BulletproofGlass", 15), });
                blockDefinitions["CubeBlock/Window1x1Flat"] = new BlockDefinition(new Component[] { new Component("Girder", 10), new Component("BulletproofGlass", 15), new Component("BulletproofGlass", 10), });
                blockDefinitions["CubeBlock/Window1x1FlatInv"] = new BlockDefinition(new Component[] { new Component("Girder", 10), new Component("BulletproofGlass", 15), new Component("BulletproofGlass", 10), });
                blockDefinitions["CubeBlock/Window3x3Flat"] = new BlockDefinition(new Component[] { new Component("Girder", 40), new Component("BulletproofGlass", 160), new Component("BulletproofGlass", 36), });
                blockDefinitions["CubeBlock/Window3x3FlatInv"] = new BlockDefinition(new Component[] { new Component("Girder", 40), new Component("BulletproofGlass", 160), new Component("BulletproofGlass", 36), });
                blockDefinitions["CubeBlock/Window2x3Flat"] = new BlockDefinition(new Component[] { new Component("Girder", 25), new Component("BulletproofGlass", 115), new Component("BulletproofGlass", 25), });
                blockDefinitions["CubeBlock/Window2x3FlatInv"] = new BlockDefinition(new Component[] { new Component("Girder", 25), new Component("BulletproofGlass", 115), new Component("BulletproofGlass", 25), });
                blockDefinitions["Conveyor/SmallBlockConveyor"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 2), new Component("Construction", 4), new Component("Motor", 1), new Component("InteriorPlate", 2), });
                blockDefinitions["Conveyor/LargeBlockConveyor"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 10), new Component("Construction", 20), new Component("SmallTube", 20), new Component("Motor", 6), new Component("Construction", 10), new Component("InteriorPlate", 10), });
                blockDefinitions["Collector/Collector"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 30), new Component("Construction", 50), new Component("SmallTube", 12), new Component("Motor", 8), new Component("Display", 4), new Component("Computer", 10), new Component("SteelPlate", 15), });
                blockDefinitions["Collector/CollectorSmall"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 25), new Component("Construction", 35), new Component("SmallTube", 12), new Component("Motor", 8), new Component("Display", 2), new Component("Computer", 8), new Component("SteelPlate", 10), });
                blockDefinitions["ShipConnector/Connector"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 130), new Component("Construction", 40), new Component("SmallTube", 12), new Component("Motor", 8), new Component("Computer", 20), new Component("SteelPlate", 20), });
                blockDefinitions["ShipConnector/ConnectorSmall"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 5), new Component("Construction", 4), new Component("SmallTube", 2), new Component("Motor", 1), new Component("Computer", 4), new Component("SteelPlate", 2), });
                blockDefinitions["ShipConnector/ConnectorMedium"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 15), new Component("Construction", 12), new Component("SmallTube", 6), new Component("Motor", 6), new Component("Computer", 6), new Component("SteelPlate", 6), });
                blockDefinitions["ConveyorConnector/ConveyorTube"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 10), new Component("Construction", 20), new Component("SmallTube", 12), new Component("Motor", 6), new Component("InteriorPlate", 4), });
                blockDefinitions["ConveyorConnector/ConveyorTubeSmall"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 1), new Component("Motor", 1), new Component("Construction", 1), });
                blockDefinitions["ConveyorConnector/ConveyorTubeMedium"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 8), new Component("Construction", 20), new Component("SmallTube", 10), new Component("Motor", 6), new Component("InteriorPlate", 2), });
                blockDefinitions["ConveyorConnector/ConveyorFrameMedium"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 4), new Component("Construction", 12), new Component("SmallTube", 5), new Component("Motor", 2), new Component("InteriorPlate", 1), });
                blockDefinitions["ConveyorConnector/ConveyorTubeCurved"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 10), new Component("Construction", 20), new Component("SmallTube", 12), new Component("Motor", 6), new Component("InteriorPlate", 4), });
                blockDefinitions["ConveyorConnector/ConveyorTubeSmallCurved"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 1), new Component("Motor", 1), new Component("Construction", 1), });
                blockDefinitions["ConveyorConnector/ConveyorTubeCurvedMedium"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 2), new Component("Construction", 20), new Component("SmallTube", 10), new Component("Motor", 6), new Component("InteriorPlate", 5), });
                blockDefinitions["Conveyor/SmallShipConveyorHub"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 20), new Component("Construction", 30), new Component("SmallTube", 25), new Component("Motor", 2), new Component("Construction", 15), new Component("InteriorPlate", 5), });
                blockDefinitions["ConveyorSorter/LargeBlockConveyorSorter"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 40), new Component("Construction", 100), new Component("SmallTube", 50), new Component("Computer", 20), new Component("Motor", 2), new Component("Construction", 20), new Component("InteriorPlate", 10), });
                blockDefinitions["ConveyorSorter/MediumBlockConveyorSorter"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 4), new Component("Construction", 10), new Component("SmallTube", 5), new Component("Computer", 5), new Component("Motor", 2), new Component("Construction", 2), new Component("InteriorPlate", 1), });
                blockDefinitions["ConveyorSorter/SmallBlockConveyorSorter"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 4), new Component("Construction", 10), new Component("SmallTube", 5), new Component("Computer", 5), new Component("Motor", 2), new Component("Construction", 2), new Component("InteriorPlate", 1), });
                blockDefinitions["VirtualMass/VirtualMassLarge"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 30), new Component("Superconductor", 20), new Component("Construction", 30), new Component("Computer", 20), new Component("GravityGenerator", 9), new Component("SteelPlate", 60), });
                blockDefinitions["VirtualMass/VirtualMassSmall"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 1), new Component("Superconductor", 2), new Component("Construction", 2), new Component("Computer", 2), new Component("GravityGenerator", 1), new Component("SteelPlate", 2), });
                blockDefinitions["SpaceBall/SpaceBallLarge"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 90), new Component("Construction", 30), new Component("Computer", 20), new Component("GravityGenerator", 3), new Component("SteelPlate", 135), });
                blockDefinitions["SpaceBall/SpaceBallSmall"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 50), new Component("Construction", 10), new Component("Computer", 7), new Component("GravityGenerator", 1), new Component("SteelPlate", 20), });
                blockDefinitions["Wheel/SmallRealWheel1x1"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 1), new Component("Construction", 5), new Component("LargeTube", 1), new Component("SteelPlate", 1), });
                blockDefinitions["Wheel/SmallRealWheel"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 3), new Component("Construction", 10), new Component("LargeTube", 1), new Component("SteelPlate", 2), });
                blockDefinitions["Wheel/SmallRealWheel5x5"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 4), new Component("Construction", 15), new Component("LargeTube", 2), new Component("SteelPlate", 3), });
                blockDefinitions["Wheel/RealWheel1x1"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 4), new Component("Construction", 20), new Component("LargeTube", 4), new Component("SteelPlate", 4), });
                blockDefinitions["Wheel/RealWheel"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 6), new Component("Construction", 25), new Component("LargeTube", 6), new Component("SteelPlate", 6), });
                blockDefinitions["Wheel/RealWheel5x5"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 8), new Component("Construction", 30), new Component("LargeTube", 8), new Component("SteelPlate", 8), });
                blockDefinitions["Wheel/SmallRealWheel1x1mirrored"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 1), new Component("Construction", 5), new Component("LargeTube", 1), new Component("SteelPlate", 1), });
                blockDefinitions["Wheel/SmallRealWheelmirrored"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 3), new Component("Construction", 10), new Component("LargeTube", 1), new Component("SteelPlate", 2), });
                blockDefinitions["Wheel/SmallRealWheel5x5mirrored"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 4), new Component("Construction", 15), new Component("LargeTube", 2), new Component("SteelPlate", 3), });
                blockDefinitions["Wheel/RealWheel1x1mirrored"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 4), new Component("Construction", 20), new Component("LargeTube", 4), new Component("SteelPlate", 4), });
                blockDefinitions["Wheel/RealWheelmirrored"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 6), new Component("Construction", 25), new Component("LargeTube", 6), new Component("SteelPlate", 6), });
                blockDefinitions["Wheel/RealWheel5x5mirrored"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 8), new Component("Construction", 30), new Component("LargeTube", 8), new Component("SteelPlate", 8), });
                blockDefinitions["Wheel/Wheel1x1"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 4), new Component("Construction", 20), new Component("LargeTube", 4), new Component("SteelPlate", 4), });
                blockDefinitions["Wheel/SmallWheel1x1"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 1), new Component("Construction", 5), new Component("LargeTube", 1), new Component("SteelPlate", 1), });
                blockDefinitions["Wheel/Wheel3x3"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 6), new Component("Construction", 25), new Component("LargeTube", 6), new Component("SteelPlate", 6), });
                blockDefinitions["Wheel/SmallWheel3x3"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 3), new Component("Construction", 10), new Component("LargeTube", 1), new Component("SteelPlate", 2), });
                blockDefinitions["Wheel/Wheel5x5"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 8), new Component("Construction", 30), new Component("LargeTube", 8), new Component("SteelPlate", 8), });
                blockDefinitions["Wheel/SmallWheel5x5"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 4), new Component("Construction", 15), new Component("LargeTube", 2), new Component("SteelPlate", 3), });
                blockDefinitions["ShipGrinder/LargeShipGrinder"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 15), new Component("Construction", 25), new Component("LargeTube", 1), new Component("Motor", 4), new Component("Computer", 2), new Component("Construction", 5), new Component("SteelPlate", 5), });
                blockDefinitions["ShipGrinder/SmallShipGrinder"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 10), new Component("Construction", 15), new Component("SmallTube", 4), new Component("Motor", 4), new Component("Computer", 2), new Component("Construction", 2), new Component("SteelPlate", 2), });
                blockDefinitions["ShipWelder/LargeShipWelder"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 15), new Component("Construction", 25), new Component("LargeTube", 1), new Component("Motor", 2), new Component("Computer", 2), new Component("Construction", 5), new Component("SteelPlate", 5), });
                blockDefinitions["ShipWelder/SmallShipWelder"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 10), new Component("Construction", 15), new Component("SmallTube", 6), new Component("Motor", 2), new Component("Computer", 2), new Component("Construction", 2), new Component("SteelPlate", 2), });
                blockDefinitions["MergeBlock/LargeShipMergeBlock"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 5), new Component("Construction", 15), new Component("Motor", 2), new Component("LargeTube", 6), new Component("Computer", 2), new Component("SteelPlate", 7), });
                blockDefinitions["MergeBlock/SmallShipMergeBlock"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 1), new Component("Construction", 5), new Component("Motor", 1), new Component("SmallTube", 2), new Component("Computer", 1), new Component("SteelPlate", 3), });
                blockDefinitions["CubeBlock/ArmorCenter"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 125), new Component("SteelPlate", 15), });
                blockDefinitions["MyProgrammableBlock/LargeProgrammableBlock"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 11), new Component("Construction", 4), new Component("LargeTube", 2), new Component("Motor", 1), new Component("Display", 1), new Component("Computer", 2), new Component("SteelPlate", 10), });
                blockDefinitions["CubeBlock/ArmorCorner"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 105), new Component("SteelPlate", 15), });
                blockDefinitions["CubeBlock/ArmorInvCorner"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 120), new Component("SteelPlate", 15), });
                blockDefinitions["CubeBlock/ArmorSide"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 115), new Component("SteelPlate", 15), });
                blockDefinitions["CubeBlock/SmallArmorCenter"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 3), new Component("SteelPlate", 2), });
                blockDefinitions["CubeBlock/SmallArmorCorner"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 3), new Component("SteelPlate", 2), });
                blockDefinitions["CubeBlock/SmallArmorInvCorner"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 3), new Component("SteelPlate", 2), });
                blockDefinitions["CubeBlock/SmallArmorSide"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 3), new Component("SteelPlate", 2), });
                blockDefinitions["LaserAntenna/LargeBlockLaserAntenna"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 40), new Component("Construction", 40), new Component("Motor", 16), new Component("Detector", 30), new Component("RadioCommunication", 20), new Component("Superconductor", 100), new Component("Computer", 50), new Component("BulletproofGlass", 4), new Component("SteelPlate", 10), });
                blockDefinitions["LaserAntenna/SmallBlockLaserAntenna"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 6), new Component("SmallTube", 10), new Component("Construction", 10), new Component("Motor", 5), new Component("RadioCommunication", 5), new Component("Superconductor", 10), new Component("Computer", 30), new Component("BulletproofGlass", 2), new Component("SteelPlate", 4), });
                blockDefinitions["AirtightHangarDoor/(null)"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 250), new Component("Construction", 15), new Component("SmallTube", 40), new Component("Motor", 16), new Component("Computer", 2), new Component("Construction", 25), new Component("SteelPlate", 100), });
                blockDefinitions["AirtightSlideDoor/LargeBlockSlideDoor"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 5), new Component("Construction", 15), new Component("SmallTube", 4), new Component("Motor", 4), new Component("Display", 1), new Component("Computer", 2), new Component("Construction", 25), new Component("BulletproofGlass", 15), new Component("SteelPlate", 15), });
                blockDefinitions["Parachute/LgParachute"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 5), new Component("Construction", 25), new Component("SmallTube", 5), new Component("Motor", 3), new Component("Computer", 2), new Component("SteelPlate", 4), });
                blockDefinitions["Parachute/SmParachute"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 1), new Component("Construction", 2), new Component("SmallTube", 1), new Component("Motor", 1), new Component("Computer", 1), new Component("SteelPlate", 1), });
                blockDefinitions["Cockpit/LargeBlockDesk"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 20), new Component("Construction", 20), new Component("InteriorPlate", 10), new Component("Construction", 10), });
                blockDefinitions["Cockpit/LargeBlockDeskCorner"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 15), new Component("Construction", 15), new Component("InteriorPlate", 5), new Component("Construction", 5), });
                blockDefinitions["Kitchen/LargeBlockKitchen"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 20), new Component("Construction", 30), new Component("LargeTube", 6), new Component("Motor", 6), new Component("BulletproofGlass", 4), });
                blockDefinitions["CryoChamber/LargeBlockBed"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 30), new Component("Construction", 20), new Component("SmallTube", 8), new Component("BulletproofGlass", 10), new Component("Construction", 10), });
                blockDefinitions["CargoContainer/LargeBlockLockerRoom"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 30), new Component("Construction", 20), new Component("Display", 4), new Component("BulletproofGlass", 10), new Component("Construction", 10), });
                blockDefinitions["CargoContainer/LargeBlockLockerRoomCorner"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 25), new Component("Construction", 15), new Component("Display", 4), new Component("BulletproofGlass", 10), new Component("Construction", 15), });
                blockDefinitions["Planter/LargeBlockPlanters"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 10), new Component("Construction", 10), new Component("SmallTube", 8), new Component("BulletproofGlass", 8), new Component("Construction", 10), });
                blockDefinitions["Cockpit/LargeBlockCouch"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 20), new Component("Construction", 20), new Component("InteriorPlate", 10), new Component("Construction", 10), });
                blockDefinitions["CargoContainer/LargeBlockLockers"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 20), new Component("Construction", 10), new Component("Display", 3), new Component("Computer", 2), new Component("Construction", 10), });
                blockDefinitions["Cockpit/LargeBlockBathroomOpen"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 30), new Component("Construction", 15), new Component("SmallTube", 8), new Component("Motor", 4), new Component("LargeTube", 2), new Component("Construction", 15), });
                blockDefinitions["Cockpit/LargeBlockToilet"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 10), new Component("Construction", 10), new Component("SmallTube", 2), new Component("Motor", 2), new Component("LargeTube", 1), new Component("Construction", 5), });
                blockDefinitions["Projector/LargeBlockConsole"] = new BlockDefinition(new Component[] { new Component("InteriorPlate", 20), new Component("Construction", 20), new Component("Computer", 8), new Component("Display", 10), new Component("Construction", 10), });
                blockDefinitions["Cockpit/SmallBlockCockpitIndustrial"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 10), new Component("Construction", 20), new Component("MetalGrid", 10), new Component("Motor", 2), new Component("Display", 6), new Component("Computer", 20), new Component("BulletproofGlass", 60), new Component("SmallTube", 10), });
                blockDefinitions["Cockpit/LargeBlockCockpitIndustrial"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 20), new Component("Construction", 30), new Component("MetalGrid", 15), new Component("Motor", 2), new Component("Display", 10), new Component("Computer", 60), new Component("BulletproofGlass", 80), new Component("SmallTube", 10), });
                blockDefinitions["DebugSphere1/DebugSphereLarge"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 10), new Component("Computer", 20), });
                blockDefinitions["DebugSphere2/DebugSphereLarge"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 10), new Component("Computer", 20), });
                blockDefinitions["DebugSphere3/DebugSphereLarge"] = new BlockDefinition(new Component[] { new Component("SteelPlate", 10), new Component("Computer", 20), });
            }


            public BlockDefinitions()
            {
                FillDictionary();
            }

            public BlockDefinition GetDefinition(string key)
            {
                return blockDefinitions[key.Remove(0, 16)];
            }

            public class BlockDefinition
            {
                public Component[] components;

                public BlockDefinition(Component[] components)
                {
                    this.components = components;
                }
            }

            public string GetFullComponentName(string key)
            {

                //TODO prolly a proper list of these -.-

                string result = key;

                switch (key)
                {
                    case "Construction":
                    case "Girder":
                    case "Motor":
                    case "Computer":
                    case "Reactor":
                    case "Thrust":
                    case "GravityGenerator":
                    case "Medical":
                    case "RadioCommunication":
                    case "Detector":
                    case "Explosives":
                        result += "Component";
                        break;
                }

                return "MyObjectBuilder_BlueprintDefinition/" + result;

            }

            public class Component
            {
                public string id;
                public int count;

                public Component(string id, int count)
                {
                    this.id = id;
                    this.count = count;
                }
            }
        }
    }
}
